### ISSUE TITLE
Evaluate pip package missing from requirements.txt

### ISSUE THREAD

**Issue by cameronshinn** [IST-DASLab/TACO4NLP#1]
After going through the environment setup in conda, I found that I was still missing the "evaluate" package that is needed in [`run_translation.py`](https://github.com/IST-DASLab/TACO4NLP/blob/3bfb8be015efd9718d2d9737b08519288317afb8/translation/run_translation.py#L32).

**Comment by Godofnothing** [comment]
@cameronshinn  thanks for your comment I'll add this dependency to requirements
